// ---------------------------
// This file was generated by Nango (v0.58.4)
// You can version this file
// ---------------------------

export interface SlackUser {
  id: string;
  team_id: string;
  name: string;
  deleted: boolean;
  tz: string;
  tz_label: string;
  tz_offset: number;
  profile: {  avatar_hash: string;
  real_name: string | null;
  display_name: string | null;
  real_name_normalized: string | null;
  display_name_normalized: string | null;
  email: string | null;
  image_original: string | null | undefined;};
  is_admin: boolean;
  is_owner: boolean;
  is_primary_owner: boolean;
  is_restricted: boolean;
  is_ultra_restricted: boolean;
  is_bot: boolean;
  updated: number;
  is_app_user: boolean;
  raw_json: string;
};

export interface SendMessageInput {
  channel: string;
  text: string;
};

export interface SendMessageOutput {
  ok: boolean;
  channel?: string | undefined;
  ts?: string | undefined;
  message?: string | undefined;
  warning?: string | undefined;
  error?: string | undefined;
  raw_json: string;
};

export interface IdEntity {
  id: string;
};

export interface DocumentMetadata {
  files: string[] | undefined;
  folders: string[] | undefined;
};

export interface Document {
  id: string;
  url: string;
  title: string;
  mimeType: string;
  updatedAt: string;
};

export interface JSONDocument {
  documentId: string;
  title: string;
  url: string;
  tabs: Record<string, any>[];
  revisionId: string;
  suggestionsViewMode: 'DEFAULT_FOR_CURRENT_ACCESS' | 'SUGGESTIONS_INLINE' | 'PREVIEW_SUGGESTIONS_ACCEPTED' | 'PREVIEW_WITHOUT_SUGGESTIONS';
  body: Record<string, any>;
  headers: Record<string, any>;
  footers: Record<string, any>;
  footnotes: Record<string, any>;
  documentStyle: Record<string, any>;
  suggestedDocumentStyleChanges: Record<string, any>;
  namedStyles: Record<string, any>;
  suggestedNamedStylesChanges: Record<string, any>;
  lists: Record<string, any>;
  namedRanges: Record<string, any>;
  inlineObjects: Record<string, any>;
  positionedObjects: Record<string, any>;
};

/** @deprecated It is recommended to use a Model */
export type Anonymous_googledrive_action_fetchdocument_output = string
