// ---------------------------
// This file was generated by Nango (v0.42.22)
// You can version this file
// ---------------------------

export interface SlackUser {
  id: string;
  fullName: string;
  deleted: boolean;
  avatar: string;
};

export interface SlackSendMessageInput {
  userSlackId: string;
};
