// ---------------------------
// This file was generated by Nango (v0.40.8)
// You can version this file
// ---------------------------

export interface SlackUser {
  id: number;
  fullName: string;
  deleted: boolean;
};

export interface SlackSendMessageInput {
  userSlackId: string;
};
