// ---------------------------
// This file was generated by Nango (v0.68.1)
// You can version this file
// ---------------------------

export interface SyncMetadata_one_drive_userfiles {}

export interface OneDriveFile {
    id: string;
    name: string;
    etag: string;
    cTag: string;
    is_folder: boolean;
    mime_type: string | null;
    path: string;
    raw_source: {};
    updated_at: string;
    created_at: string;
    blob_size: number;
    drive_id: string;
}

export interface SyncMetadata_one_drive_userfilesselection {
    drives: string[];
    pickedFiles: { driveId: string; fileIds: string[] }[];
}

export interface OneDriveFileSelection {
    id: string;
    name: string;
    etag: string;
    cTag: string;
    is_folder: boolean;
    mime_type: string | null;
    path: string;
    raw_source: {};
    updated_at: string;
    created_at: string;
    blob_size: number;
    drive_id: string;
}

export interface ActionInput_one_drive_fetchfile {
    driveId: string;
    itemId: string;
}

export interface ActionOutput_one_drive_fetchfile {
    id: string;
    download_url: string | null;
}

export type ActionInput_one_drive_listdrives = void;

export interface ActionOutput_one_drive_listdrives {
    drives: { id: string; name: string; createdDateTime: string; webUrl: string }[];
}
